// 本教程讨论的内容：

// 什么是 panic？
// 什么时候应该使用 panic？
// panic 示例
// 发生 panic 时的 defer
// recover
// panic，recover 和 Go 协程
// 运行时 panic
// 恢复后获得堆栈跟踪


package main

import (
	ch "ch32"
)

func main() {
	// 第一个示例
	//ch.MainCall1()

	// 第二个示例
	//ch.MainCall2()

	// 第三个示例
	//ch.MainCall3()

	// 第四个示例
	ch.MainCall4()

	// 第五个示例
	//ch.MainCall5()

	// 第六个示例
	//ch.MainCall6()

	// 第七个示例
	//ch.MainCall7()

	// 第八个示例
	//ch.MainCall8()

	// 第九个示例
	//ch.MainCall9()

	// 第十个示例
	//ch.MainCall10()

}
